### PR TITLE
Add a function to parse and evaluate an expression

### PR DESCRIPTION
**Pull request by gsoleilhac**
This PR adds the function `runexpr` which passes forward a string to the host, which is then parsed and evaluated on the server.

e.g. : `runexpr("x = 3 ; for i = 1:x ; println(i) ; end", output=buffer)`

I reorganized the code to handle running a file versus running an expression on the server and the first thing the server reads is now the mode, which can be `token_runfile`, `token_runexpr` or `token_exit`.
Exiting the server is now done by the function `sendExitCode()`.

I had a few issues when trying to add a test and resolved it by closing the connection before leaving the function `serve()`

### CODE REVIEW

**Comment by dmolina** [comment]
Thank you! It is an interesting option and meanwhile you have improved my code. 
Please, could you update the documentation to include these options? I could do it, but maybe it is better than you do it.

**Comment by gsoleilhac** [comment]
Will do :)

**Comment by gsoleilhac** [comment]
Okay, I added a section with the same CSV -> DataFrame example. 

Maybe we could expand about how included files or expressions affect the global state of the server? But that depends on your plans for the package and if you want to follow Mason's suggestion on Discourse to run everything in it's own module.

**Comment by dmolina** [comment]
Thank you, I have already merged it. In few days I expect to have time to improve it a little more. And yes, I want to follow Mason's suggestion ab out run files in its own module.

**Pull request merged**
